version: '3'

services:
  aws_ci_poc_mvc:
    image: awscipocmvc:dev
    build:
      args:
        source: obj/Docker/empty/
    volumes:
      - D:\Work\dev\src\net\aws_ci_poc\aws_ci_poc_mvc\aws_ci_poc_mvc:C:\inetpub\wwwroot
      - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Remote Debugger:C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    environment:
      - DEV_ENVIRONMENT=1
      - VBCSCOMPILER_TTL=604800

